spring:
  application:
    name: matching-ms

server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: /matching-ms

groq:
  api:
    key: your-groq-api-key-here
    url: https://api.groq.com
    model: llama3-70b-8192

user-info-ms:
  url: https://career-bridge-l7zu.onrender.com/user-info-ms

vacancy-ms:
  url: https://aztu-career-bridge-vacancy-ms.onrender.com/vacancy-ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html